QUESTION_OVERWRITE = "Overwrite image files?"
YUNET_MODEL = "face_detection_yunet_2023mar.onnx"

# Static Pillow extension-to-format map. Keeping this static avoids calling
# Image.registered_extensions() at import time, which imports/registers every
# Pillow image plugin before autocrop has done any work.
IMAGE_FORMATS_BY_EXTENSION = {
    ".apng": "PNG",
    ".avif": "AVIF",
    ".avifs": "AVIF",
    ".blp": "BLP",
    ".bmp": "BMP",
    ".bufr": "BUFR",
    ".bw": "SGI",
    ".cur": "CUR",
    ".dcx": "DCX",
    ".dds": "DDS",
    ".dib": "DIB",
    ".emf": "WMF",
    ".eps": "EPS",
    ".fit": "FITS",
    ".fits": "FITS",
    ".flc": "FLI",
    ".fli": "FLI",
    ".ftc": "FTEX",
    ".ftu": "FTEX",
    ".gbr": "GBR",
    ".gif": "GIF",
    ".grib": "GRIB",
    ".h5": "HDF5",
    ".hdf": "HDF5",
    ".icb": "TGA",
    ".icns": "ICNS",
    ".ico": "ICO",
    ".iim": "IPTC",
    ".im": "IM",
    ".j2c": "JPEG2000",
    ".j2k": "JPEG2000",
    ".jfif": "JPEG",
    ".jp2": "JPEG2000",
    ".jpc": "JPEG2000",
    ".jpe": "JPEG",
    ".jpeg": "JPEG",
    ".jpf": "JPEG2000",
    ".jpg": "JPEG",
    ".jpx": "JPEG2000",
    ".mpeg": "MPEG",
    ".mpg": "MPEG",
    ".mpo": "MPO",
    ".msp": "MSP",
    ".palm": "PALM",
    ".pbm": "PPM",
    ".pcd": "PCD",
    ".pcx": "PCX",
    ".pdf": "PDF",
    ".pfm": "PPM",
    ".pgm": "PPM",
    ".png": "PNG",
    ".pnm": "PPM",
    ".ppm": "PPM",
    ".ps": "EPS",
    ".psd": "PSD",
    ".pxr": "PIXAR",
    ".qoi": "QOI",
    ".ras": "SUN",
    ".rgb": "SGI",
    ".rgba": "SGI",
    ".sgi": "SGI",
    ".tga": "TGA",
    ".tif": "TIFF",
    ".tiff": "TIFF",
    ".vda": "TGA",
    ".vst": "TGA",
    ".webp": "WEBP",
    ".wmf": "WMF",
    ".xbm": "XBM",
    ".xpm": "XPM",
}

INPUT_FILETYPES = frozenset(IMAGE_FORMATS_BY_EXTENSION)
